import { CalendarEntryData } from "@/types/calendar";

export const mockCalendarEntries: Record<string, CalendarEntryData> = {
  "2026-09-18": {
    id: "entry-sep-18",
    dateKey: "2026-09-18",
    dateFormatted: "18 September 2026",
    dayOfWeek: "Friday",
    title: "A New Creative Spark",
    content:
      "Today I had an interesting idea for a new project.\n\nI want to explore it and see where it takes me. Typing on a keyboard that transforms into living handwriting feels surprisingly intimate. I stayed up late drafting the initial concept.",
    moodEmoji: "😊",
    moodLabel: "Inspired",
    inkColor: "midnight",
    diaryName: "My Personal Journal",
    wordCount: 42,
  },
  "2026-09-15": {
    id: "entry-sep-15",
    dateKey: "2026-09-15",
    dateFormatted: "15 September 2026",
    dayOfWeek: "Tuesday",
    title: "Deep Work Sprint",
    content:
      "Unbelievable momentum today. Worked for five uninterrupted hours with black coffee and ambient rain sounds. Everything clicked into place without friction.",
    moodEmoji: "🔥",
    moodLabel: "Energized",
    inkColor: "carbon",
    diaryName: "Creative Sparks",
    wordCount: 31,
  },
  "2026-09-11": {
    id: "entry-sep-11",
    dateKey: "2026-09-11",
    dateFormatted: "11 September 2026",
    dayOfWeek: "Friday",
    title: "Heavy Thoughts & Rain",
    content:
      "Felt overwhelmed by the noise of modern life today. Some days you just want to step away from all the screens and sit quietly by the garden window. Allowed myself to rest.",
    moodEmoji: "😔",
    moodLabel: "Melancholy",
    inkColor: "sepia",
    diaryName: "My Personal Journal",
    wordCount: 38,
  },
  "2026-09-08": {
    id: "entry-sep-08",
    dateKey: "2026-09-08",
    dateFormatted: "8 September 2026",
    dayOfWeek: "Tuesday",
    title: "Walking by the Lake",
    content:
      "Watched the mist rise off the water at dusk. Autumn is creeping in quietly, turning the maples amber. Grateful for peace and simple routines.",
    moodEmoji: "🌿",
    moodLabel: "Peaceful",
    inkColor: "forest",
    diaryName: "Travel & Wandering",
    wordCount: 33,
  },
  "2026-09-03": {
    id: "entry-sep-03",
    dateKey: "2026-09-03",
    dateFormatted: "3 September 2026",
    dayOfWeek: "Thursday",
    title: "Fresh Pages for a New Month",
    content:
      "September has arrived. Cleaned my desk, sharpened my fountain pens, and set my intentions for the season ahead. Clarity is a gift.",
    moodEmoji: "✨",
    moodLabel: "Optimistic",
    inkColor: "midnight",
    diaryName: "My Personal Journal",
    wordCount: 29,
  },
  "2026-09-22": {
    id: "entry-sep-22",
    dateKey: "2026-09-22",
    dateFormatted: "22 September 2026",
    dayOfWeek: "Tuesday",
    title: "Equinox Evening",
    content:
      "Equal night and day. The cool breeze carries the scent of chimney smoke and damp pine needles. An autumn equinox to remember.",
    moodEmoji: "🌙",
    moodLabel: "Calm",
    inkColor: "sepia",
    diaryName: "My Personal Journal",
    wordCount: 28,
  },
  "2026-10-04": {
    id: "entry-oct-04",
    dateKey: "2026-10-04",
    dateFormatted: "4 October 2026",
    dayOfWeek: "Sunday",
    title: "Sunday Book Haul",
    content:
      "Visited the antiquarian bookstore down the lane. Found three hardcover volumes of letters and a lovely brass bookmark.",
    moodEmoji: "😊",
    moodLabel: "Joyful",
    inkColor: "burgundy",
    diaryName: "Travel & Wandering",
    wordCount: 26,
  },
};
